# https://golangci-lint.run/usage/configuration/#config-file

run:
  modules-download-mode: readonly
  deadline: 2m
  go: "1.17" # TODO: change to 1.18 when most linters support it, see https://github.com/golangci/golangci-lint/issues/2649
linters-settings:
  errcheck:
    check-type-assertions: true # default false
  gosimple:
    go: "1.17" # default '1.13'
  funlen:
    lines: 60
    statements: 40
  govet:
    check-shadowing: true
    enable-all: true
    disable:
      - fieldalignment
  staticcheck:
    go: "1.17" # default '1.13'
  stylecheck:
    go: "1.17" # default '1.13'
  golint:
    min-confidence: 0.8
  gofmt:
    simplify: true
  gocyclo:
    min-complexity: 10
  maligned:
    suggest-new: true
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/gtforge)
      - prefix(github.com/gtforge/newrelicutil/v2)
  dupl:
    threshold: 100
  lll:
    line-length: 140
    tab-width: 4
  unused:
    check-exported: true
    go: "1.17" # default '1.13'
  nakedret:
    max-func-lines: 30
  prealloc:
    simple: true
    range-loops: true # Report preallocation suggestions on range loops, true by default
    for-loops: false # Report preallocation suggestions on for loops, false by default
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
      - experimental
      - opinionated
# https://golangci-lint.run/usage/linters/
linters:
  disable-all: true
  enable:
    # MUST: detect bugs
    - asciicheck
    - errcheck
    - govet
    - exportloopref
    - ineffassign
    - gocritic
    - gosec
    - depguard
    - staticcheck
    - bodyclose
    - rowserrcheck
    - bidichk
    - contextcheck
    - durationcheck
    - errchkjson
    - errorlint
    - exhaustive
    - sqlclosecheck
    - noctx
    - nilerr
    - makezero
    # MUST: performance / efficient
    - prealloc
    # CHALLENGE: do not disable
    - gocognit
    - goconst
    - nakedret
    - gocyclo
    - funlen
    - gosimple
    - misspell
    - gofmt
    - goimports
    - maintidx
    - cyclop
    # OPTIONAL: it is good to use, but it is not strict
    - lll
    # - deadcode # is deprecated (since v1.49.0)
    - dogsled
    - dupl
    - gochecknoinits
    - revive
    # - structcheck # is deprecated (since v1.49.0)
    - stylecheck
    - typecheck
    - unconvert
    - unparam
    - unused
    # - varcheck # is deprecated (since v1.49.0)
    - whitespace
    - gofumpt
#    - gochecknoglobals
    - wsl
    # TODO: enable godox after implement all main features in metrics library
    #- godox
    # NEW: just added
#    - gomnd
    - goprintffuncname
    - nolintlint
#   - godot # disable because it not convenient
#   - goerr113
    - nestif
#   - testpackage
    - gomodguard
    - gomoddirectives
#   - wrapcheck
    - wastedassign
#    - paralleltest
    - tparallel
    - thelper
    - promlinter
    - predeclared
    - importas
    - goheader
    - gci
    - containedctx
    - decorder
    - errname
#   - exhaustivestruct
    - forbidigo
    - forcetypeassert
#   - varnamelen
    - tenv
#   - tagliatelle
    - nlreturn
    - nilnil
    # - ifshort # is deprecated (since v1.49.0)
    - grouper
#   - ireturn
  fast: false
issues:
  exclude-rules:
    - path: main.go
      linters:
        # it's possible to have long main functions
        - funlen
    - path: .*_test.go
      linters:
        # it's possible to use global var in tests
        - gochecknoglobals
        # it's possible to have long functions in test
        - funlen
        # allow for long example comments in tests
        - lll
    # go generate may be long
