name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    branches: [ "master" ]

env:
  BUNDLE_GITHUB__COM: ${{secrets.GH_ACCESS_TOKEN}}
  GOPRIVATE: github.com/gtforge

jobs:
  ci:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Setup go and golangci-lint cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/golangci-lint
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: GitHub private access
        run: git config --global url.https://${{env.BUNDLE_GITHUB__COM}}@github.com/.insteadOf https://github.com/

      - name: Install Go linter
        run: make lint-install

      - name: Run tests
        run: make test

      - name: Run linter
        run: make lint
